/* This file is generated automatically by linuxtoavr
 * Do not modify this file - any modifications will be overwritten
 * This is for a including in an array defined as:
 * struct tableentry { const char *name, const char *defines }
 * Both defines and name are null terminated strings
 * The defines are made using sounds.h which should be included before this file
 * The table is sorted alphabectically
 *
 * To send an email to the maker of linuxtoavr telling him how much you like it please write to:
 * <jhuntnz@users.sf.net (Subject: I love linuxtoavr!)
 * Please include Visa card details so I can deduct US$20 - Thanks
 *
 * This file is generated for language E
 */

#include "soundcontrol.h"

/* Dummy headers for Dynamic C */
/*** Beginheader sounds_E_c */
#ifdef TARGET_RABBIT
void sounds_E_c();

#asm
xxxsounds_E_c: equ sounds_E_c
#endasm

#endif /* TARGET_RABBIT */
/*** endheader */

#ifdef TARGET_RABBIT
void sounds_E_c() { }
#endif /* TARGET_RABBIT */



E_TABLE_DECL
 "April"              , EW_April                ,
 "August"              , EW_August                ,
 "Celsius"              , EW_Celsius                ,
 "December"              , EW_December                ,
 "Fahrenheit"              , EW_Fahrenheit                ,
 "February"              , EW_February                ,
 "Friday"              , EW_fry EW_day                ,
 "January"              , EW_January                ,
 "July"              , EW_July                ,
 "June"              , EW_June                ,
 "Mon"              , EW_Mon                ,
 "Monday"              , EW_Mon EW_day                ,
 "November"              , EW_November                ,
 "October"              , EW_October                ,
 "Ouch"              , EW_Ouch                ,
 "Satur"              , EW_Satur                ,
 "Saturday"              , EW_Satur EW_day                ,
 "September"              , EW_September                ,
 "Sunday"              , EW_sun EW_day                ,
 "Thurs"              , EW_Thurs                ,
 "Thursday"              , EW_Thurs EW_day                ,
 "Tuesday"              , EW_chews EW_day                ,
 "Wednes"              , EW_Wednes                ,
 "Wednesday"              , EW_Wednes EW_day                ,
 "a"              , EW_a                ,
 "am"              , EW_am                ,
 "and"              , EW_and                ,
 "angle"              , EW_angle                ,
 "angles"              , EW_angle PH_z                ,
 "are"              , EW_are                ,
 "at"              , EW_at                ,
 "attack"              , EW_attack                ,
 "attacks"              , EW_attack PH_s                ,
 "automatic"              , EW_automatic                ,
 "back"              , EW_back                ,
 "battery"              , EW_battery                ,
 "bearing"              , EW_bearing                ,
 "bearings"              , EW_bearing PH_z                ,
 "big"              , EW_big                ,
 "brain"              , EW_brain                ,
 "bumper"              , EW_bumper                ,
 "but"              , EW_but                ,
 "charge"              , EW_charge                ,
 "charging"              , EW_charging                ,
 "chase"              , EW_chase                ,
 "chews"              , EW_chews                ,
 "circle"              , EW_circle                ,
 "clear"              , EW_clear                ,
 "clears"              , EW_clear PH_z                ,
 "correct"              , EW_correct                ,
 "date"              , EW_date                ,
 "day"              , EW_day                ,
 "degree"              , EW_degree                ,
 "degrees"              , EW_degree PH_z                ,
 "demo"              , EW_demo                ,
 "diagnostic"              , EW_diagnostic                ,
 "digit"              , EW_digit                ,
 "digits"              , EW_digit PH_s                ,
 "distance"              , EW_distance                ,
 "eight"              , EW_eight                ,
 "eighteen"              , EW_eighteen                ,
 "eighty"              , EW_eighty                ,
 "eleven"              , EW_eleven                ,
 "enter"              , EW_enter                ,
 "enters"              , EW_enter PH_z                ,
 "error"              , EW_error                ,
 "errors"              , EW_error PH_z                ,
 "escape"              , EW_escape                ,
 "extreme"              , EW_extreme                ,
 "fifteen"              , EW_fifteen                ,
 "fifty"              , EW_fifty                ,
 "first"              , EW_first                ,
 "five"              , EW_five                ,
 "for"              , EW_four                ,
 "forty"              , EW_forty                ,
 "forward"              , EW_forward                ,
 "four"              , EW_four                ,
 "fourteen"              , EW_fourteen                ,
 "front"              , EW_front                ,
 "fry"              , EW_fry                ,
 "full"              , EW_full                ,
 "go"              , EW_go                ,
 "goes"              , EW_go PH_z                ,
 "halt"              , EW_halt                ,
 "halted"              , EW_halt PH_IH PH_d                ,
 "hello"              , EW_hello                ,
 "help"              , EW_help                ,
 "hi"              , EW_high                ,
 "high"              , EW_high                ,
 "hour"              , EW_hour                ,
 "hours"              , EW_hour PH_z                ,
 "hundred"              , EW_hundred                ,
 "in"              , EW_in                ,
 "incorrect"              , EW_in EW_correct                ,
 "intensity"              , EW_intensity                ,
 "invalid"              , EW_in EW_valid                ,
 "is"              , EW_is                ,
 "know"              , EW_no                ,
 "lattitude"              , EW_lattitude                ,
 "left"              , EW_left                ,
 "letter"              , EW_letter                ,
 "letters"              , EW_letter PH_z                ,
 "level"              , EW_level                ,
 "light"              , EW_light                ,
 "lights"              , EW_light PH_s                ,
 "lo"              , EW_low                ,
 "longitude"              , EW_longitude                ,
 "low"              , EW_low                ,
 "manual"              , EW_manual                ,
 "march"              , EW_march                ,
 "may"              , EW_may                ,
 "millimetre"              , EW_millimetre                ,
 "millimetres"              , EW_millimetre PH_z                ,
 "million"              , EW_million                ,
 "minute"              , EW_minute                ,
 "minutes"              , EW_minute PH_s                ,
 "mode"              , EW_mode                ,
 "modes"              , EW_mode PH_z                ,
 "name"              , EW_name                ,
 "names"              , EW_name PH_z                ,
 "nine"              , EW_nine                ,
 "nineteen"              , EW_nineteen                ,
 "ninety"              , EW_ninety                ,
 "no"              , EW_no                ,
 "normal"              , EW_normal                ,
 "not"              , EW_not                ,
 "number"              , EW_number                ,
 "numbers"              , EW_number PH_z                ,
 "off"              , EW_off                ,
 "on"              , EW_on                ,
 "one"              , EW_one                ,
 "oops"              , EW_oops                ,
 "our"              , EW_hour                ,
 "ours"              , EW_hour PH_z                ,
 "point"              , EW_point                ,
 "points"              , EW_point PH_s                ,
 "position"              , EW_position                ,
 "power"              , EW_power                ,
 "query"              , EW_query                ,
 "random"              , EW_random                ,
 "reset"              , EW_reset                ,
 "resets"              , EW_reset PH_s                ,
 "retreat"              , EW_retreat                ,
 "retreats"              , EW_retreat PH_s                ,
 "reverse"              , EW_reverse                ,
 "right"              , EW_right                ,
 "robot"              , EW_robot                ,
 "second"              , EW_second                ,
 "seconds"              , EW_second PH_z                ,
 "seven"              , EW_seven                ,
 "seventeen"              , EW_seventeen                ,
 "seventy"              , EW_seventy                ,
 "six"              , EW_six                ,
 "sixteen"              , EW_sixteen                ,
 "sixty"              , EW_sixty                ,
 "small"              , EW_small                ,
 "son"              , EW_sun                ,
 "sorry"              , EW_sorry                ,
 "speak"              , EW_speak                ,
 "speaks"              , EW_speak PH_s                ,
 "speed"              , EW_speed                ,
 "speeds"              , EW_speed PH_z                ,
 "stealth"              , EW_stealth                ,
 "stop"              , EW_stop                ,
 "stopped"              , EW_stop PH_t                ,
 "stops"              , EW_stop PH_s                ,
 "straight"              , EW_straight                ,
 "sun"              , EW_sun                ,
 "switch"              , EW_switch                ,
 "switches"              , EW_switch EW_is                ,
 "temperature"              , EW_temperature                ,
 "temperatures"              , EW_temperature PH_z                ,
 "ten"              , EW_ten                ,
 "test"              , EW_test                ,
 "the"              , EW_the                ,
 "third"              , EW_third                ,
 "thirteen"              , EW_thirteen                ,
 "thirty"              , EW_thirty                ,
 "thousand"              , EW_thousand                ,
 "three"              , EW_three                ,
 "tilt"              , EW_tilt                ,
 "tilts"              , EW_tilt PH_s                ,
 "time"              , EW_time                ,
 "to"              , EW_two                ,
 "too"              , EW_two                ,
 "travel"              , EW_travel                ,
 "turn"              , EW_turn                ,
 "twelve"              , EW_twelve                ,
 "twenty"              , EW_twenty                ,
 "two"              , EW_two                ,
 "valid"              , EW_valid                ,
 "version"              , EW_version                ,
 "versions"              , EW_version PH_z                ,
 "won"              , EW_one                ,
 "write"              , EW_right                ,
 "yes"              , EW_yes                ,
 "yet"              , EW_yet                ,
 "zero"              , EW_zero                ,

E_TABLE_END
